### ISSUE TITLE
Error yah

### ISSUE THREAD

**Issue by cvkjm** [anasamu/mutasi#3]
(node:18684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
LOG : Checking your key and token
LOG : Checking expired credentials
(node:18684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at C:\app\xyz\mutasi\app\routes\BRIRoute.js:67:41
    at Layer.handle [as handle_request] (C:\app\xyz\mutasi\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\app\xyz\mutasi\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\app\xyz\mutasi\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\app\xyz\mutasi\node_modules\express\lib\router\layer.js:95:5)
    at C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:335:12)
    at next (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:174:3)
    at router (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\app\xyz\mutasi\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:317:13)
    at C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:335:12)
    at next (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle [as handle_request] (C:\app\xyz\mutasi\node_modules\express\lib\router\layer.js:91:12)
(node:18684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

**Comment by banguncode** [comment]
> (node:18684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4) LOG : Checking your key and token LOG : Checking expired credentials (node:18684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined at C:\app\xyz\mutasi\app\routes\BRIRoute.js:67:41 at Layer.handle [as handle_request] (C:\app\xyz\mutasi\node_modules\express\lib\router\layer.js:95:5) at next (C:\app\xyz\mutasi\node_modules\express\lib\router\route.js:137:13) at Route.dispatch (C:\app\xyz\mutasi\node_modules\express\lib\router\route.js:112:3) at Layer.handle [as handle_request] (C:\app\xyz\mutasi\node_modules\express\lib\router\layer.js:95:5) at C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:281:22 at Function.process_params (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:335:12) at next (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:275:10) at Function.handle (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:174:3) at router (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:47:12) at Layer.handle [as handle_request] (C:\app\xyz\mutasi\node_modules\express\lib\router\layer.js:95:5) at trim_prefix (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:317:13) at C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:284:7 at Function.process_params (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:335:12) at next (C:\app\xyz\mutasi\node_modules\express\lib\router\index.js:275:10) at Layer.handle [as handle_request] (C:\app\xyz\mutasi\node_modules\express\lib\router\layer.js:91:12) (node:18684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

Perhatikan nama fieldnya gan, date bukan data, terus formatnya dd/mm/yyyy
